/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg7;

/**
 *
 * @author youssufathalla
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboarddddd
     */
   
    private InstructorManager im;
    private CourseManager cm;
    private StudentManager sm;
    private UserManager um;

    public adminDashboard(UserManager um, CourseManager cm, InstructorManager im, StudentManager sm) {
        initComponents();
       
        this.im = im;
        this.cm = cm;
        this.sm = sm;
        this.um = um;

        userIdTextField.setText("ID:" +9575);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ApproveCoursesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        userIdTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ApproveCoursesButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ApproveCoursesButton.setText("Approve Courses");
        ApproveCoursesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ApproveCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveCoursesButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Dashboard");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoutbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        userIdTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logoutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(ApproveCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(ApproveCoursesButton)
                .addGap(46, 46, 46)
                .addComponent(logoutbutton)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApproveCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveCoursesButtonActionPerformed
        this.dispose();
        new ApproveCourses(this.um, this.cm, this.im, this.sm).setVisible(true);
    }//GEN-LAST:event_ApproveCoursesButtonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        this.dispose();
        new LoginFrame(this.um, this.cm, this.im, this.sm).setVisible(true);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new adminDashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveCoursesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton mycoursesbutton;
    private javax.swing.JButton mycoursesbutton1;
    private javax.swing.JButton mycoursesbutton10;
    private javax.swing.JButton mycoursesbutton11;
    private javax.swing.JButton mycoursesbutton12;
    private javax.swing.JButton mycoursesbutton13;
    private javax.swing.JButton mycoursesbutton14;
    private javax.swing.JButton mycoursesbutton15;
    private javax.swing.JButton mycoursesbutton16;
    private javax.swing.JButton mycoursesbutton17;
    private javax.swing.JButton mycoursesbutton18;
    private javax.swing.JButton mycoursesbutton19;
    private javax.swing.JButton mycoursesbutton2;
    private javax.swing.JButton mycoursesbutton20;
    private javax.swing.JButton mycoursesbutton21;
    private javax.swing.JButton mycoursesbutton22;
    private javax.swing.JButton mycoursesbutton23;
    private javax.swing.JButton mycoursesbutton24;
    private javax.swing.JButton mycoursesbutton25;
    private javax.swing.JButton mycoursesbutton26;
    private javax.swing.JButton mycoursesbutton27;
    private javax.swing.JButton mycoursesbutton28;
    private javax.swing.JButton mycoursesbutton29;
    private javax.swing.JButton mycoursesbutton3;
    private javax.swing.JButton mycoursesbutton30;
    private javax.swing.JButton mycoursesbutton31;
    private javax.swing.JButton mycoursesbutton32;
    private javax.swing.JButton mycoursesbutton33;
    private javax.swing.JButton mycoursesbutton34;
    private javax.swing.JButton mycoursesbutton35;
    private javax.swing.JButton mycoursesbutton36;
    private javax.swing.JButton mycoursesbutton37;
    private javax.swing.JButton mycoursesbutton38;
    private javax.swing.JButton mycoursesbutton39;
    private javax.swing.JButton mycoursesbutton4;
    private javax.swing.JButton mycoursesbutton40;
    private javax.swing.JButton mycoursesbutton41;
    private javax.swing.JButton mycoursesbutton42;
    private javax.swing.JButton mycoursesbutton43;
    private javax.swing.JButton mycoursesbutton44;
    private javax.swing.JButton mycoursesbutton45;
    private javax.swing.JButton mycoursesbutton46;
    private javax.swing.JButton mycoursesbutton47;
    private javax.swing.JButton mycoursesbutton5;
    private javax.swing.JButton mycoursesbutton6;
    private javax.swing.JButton mycoursesbutton7;
    private javax.swing.JButton mycoursesbutton8;
    private javax.swing.JButton mycoursesbutton9;
    private javax.swing.JTextField userIdTextField;
    // End of variables declaration//GEN-END:variables
}
