/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author youssufathalla
 */
public class BrowseCourse extends javax.swing.JFrame {

    private Student s;
    private InstructorManager im;
    private CourseManager cm;
    private StudentManager sm;
    private UserManager um;

    public BrowseCourse(UserManager um, CourseManager cm, InstructorManager im, StudentManager sm, Student s) {
        this.s = s;
        this.im = im;
        this.cm = cm;
        this.sm = sm;
        this.um = um;
           JsonDatabase.loadCourses(cm);
        initComponents();
        loadTable();
    }

    public void loadTable() {
        DefaultTableModel m = (DefaultTableModel) SearchTable.getModel();
        m.setRowCount(0);

        ArrayList<Course> list = cm.getCourses();

for (Course c : list) {
    if ("APPROVED".equals(c.getApproval())) {
        m.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getDescription(),
            c.getInstructorId(),
            (c.getLessons() == null ? 0 : c.getLessons().size())
        });
    }
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        enrollincoursebutton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CourseId", "Title", "Description", "InstructorID", "Lessons"
            }
        ));
        jScrollPane4.setViewportView(SearchTable);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        enrollincoursebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        enrollincoursebutton.setText("Enroll in course");
        enrollincoursebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enrollincoursebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollincoursebuttonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addComponent(enrollincoursebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enrollincoursebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(131, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new StudentDashboard(this.um, this.cm, this.im, this.sm, this.s).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void enrollincoursebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollincoursebuttonActionPerformed

        int selectedRow = SearchTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to enroll in.");
            return;
        }

        DefaultTableModel m = (DefaultTableModel) SearchTable.getModel();
        int courseId = (int) m.getValueAt(selectedRow, 0);

        Course selectedCourse = null;
        for (Record r : cm.read()) {
            Course c = (Course) r;
            if (c.getCourseId() == courseId) {
                selectedCourse = c;
                break;
            }
        }

        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Selected course not found.");
            return;
        }

        if (selectedCourse.getEnrolledStudents().contains(s.getUserId())) {
            JOptionPane.showMessageDialog(this, "You are already enrolled in this course.");
            return;
        }

        s.enrollCourse(courseId);
        selectedCourse.getEnrolledStudents().add(s.getUserId());
        JsonDatabase.saveUsers(sm, im);
        JsonDatabase.saveCourses(cm);
        JOptionPane.showMessageDialog(this, "Successfully enrolled in course: " + selectedCourse.getTitle());


    }//GEN-LAST:event_enrollincoursebuttonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        DefaultTableModel m = (DefaultTableModel) SearchTable.getModel();

        String idText = searchTextField.getText() == null ? "" : searchTextField.getText().trim();

        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Course ID");
            return;
        }

        m.setRowCount(0);

        int id;
        try {
            id = Integer.parseInt(idText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Course ID must be numeric");
            return;
        }

        Course c = (Course) cm.search(id);

        if (c == null|| c.getApproval().equals("PENDING")|| c.getApproval().equals("REJECTED")) {
            JOptionPane.showMessageDialog(this, "No Course found with this ID");
            return;
        }

        m.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getDescription(),
            c.getInstructorId(),
            (c.getLessons() == null ? 0 : c.getLessons().size())
        });
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BrowseCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BrowseCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BrowseCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BrowseCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SearchTable;
    private javax.swing.JButton backButton;
    private javax.swing.JButton enrollincoursebutton;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
