/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg7;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author youssufathalla
 */
public class CourseDisplay extends javax.swing.JFrame {

    private Student s;
    private InstructorManager im;
    private CourseManager cm;
    private StudentManager sm;
    private UserManager um;
    private Course c;

    public CourseDisplay(UserManager um, CourseManager cm, InstructorManager im, StudentManager sm, Student s, Course c) {
        this.s = s;
        this.im = im;
        this.cm = cm;
        this.sm = sm;
        this.um = um;
        this.c = c;

        JsonDatabase.loadUsers(sm, im);
        JsonDatabase.loadCourses(cm);

        this.s = (Student) sm.search(s.getUserId());
        this.c = (Course) cm.search(c.getCourseId());

        initComponents();
        loadTable();
    }

    public void loadTable() {

        JsonDatabase.loadUsers(sm, im);
        this.s = (Student) sm.search(s.getUserId());

        DefaultTableModel m = (DefaultTableModel) LessonsTable.getModel();
        m.setRowCount(0);

        for (Lesson l : c.getLessons()) {
            m.addRow(new Object[]{
                l.getLessonId(),
                l.getTitle(),
                l.getContent(),
                s.isLessonCompleted(c.getCourseId(), l.getLessonId()) ? "Yes" : "No"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LessonsTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        completeBtn = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "LessonID", "Title", "Content", "Completed"
            }
        ));
        jScrollPane1.setViewportView(LessonsTable);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        completeBtn.setText("Completed");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        quizBtn.setText("Take Quiz");
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backButton)
                .addGap(64, 64, 64)
                .addComponent(quizBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(completeBtn)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(completeBtn)
                    .addComponent(quizBtn))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new StudentCourses(this.um, this.cm, this.im, this.sm, this.s).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        int selectedRow = LessonsTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a lesson first.");
            return;
        }

        int lessonId = (int) LessonsTable.getValueAt(selectedRow, 0);

        for (Lesson l : c.getLessons()) {
            if (l.getLessonId() == lessonId) {
                if (l.getQuiz() != null && !s.isQuizCompleted(c.getCourseId(), l.getLessonId())) {
                    JOptionPane.showMessageDialog(
                            this,
                            "You must complete the quiz before marking this lesson completed."
                    );
                    return;
                }
                s.markLessonCompleted(c.getCourseId(), lessonId);
                break;
            }
        }
        Certificate cert = Lab7.mc.issueCertificateIfEligible(s, c);

        JsonDatabase.saveUsers(sm, im);
        loadTable();
        JOptionPane.showMessageDialog(this, "Lesson marked as completed!");
        if (cert != null) {
            JOptionPane.showMessageDialog(this,
                    "Congratulations! You completed the course.\nCertificate ID: " + cert.getCertificateId());
        }
          

        JsonDatabase.saveUsers(sm, im);
        loadTable();
        JOptionPane.showMessageDialog(this, "Lesson marked as completed!");
    }//GEN-LAST:event_completeBtnActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        int row = LessonsTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a lesson first.");
            return;
        }

        int lessonId = (int) LessonsTable.getValueAt(row, 0);

        Lesson selectedLesson = null;
        for (Lesson l : c.getLessons()) {
            if (l.getLessonId() == lessonId) {
                selectedLesson = l;
                break;
            }
        }

        if (selectedLesson == null) {
            JOptionPane.showMessageDialog(this, "Lesson not found.");
            return;
        }

        if (selectedLesson.getQuiz() != null && s.isQuizCompleted(c.getCourseId(), selectedLesson.getLessonId())) {
            JOptionPane.showMessageDialog(this, "You have already completed this quiz.");
            return;
        }

        new QuizFrame(um, cm, im, sm, s, c, selectedLesson).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quizBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CourseDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CourseDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CourseDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CourseDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CourseDisplay().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LessonsTable;
    private javax.swing.JButton backButton;
    private javax.swing.JButton completeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quizBtn;
    // End of variables declaration//GEN-END:variables
}
