/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg7;

import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

/**
 *
 * @author hassa
 */
public class InsightsFrame extends javax.swing.JFrame {

    private managecourses parent;
    private InstructorManager im;
    private UserManager um;
    private CourseManager cm;
    private Instructor ins;
    private StudentManager sm;
    private Course c;

    /**
     * Creates new form InsightsFrame
     */
 
    public InsightsFrame(managecourses parent, CourseManager cm, InstructorManager im, StudentManager sm, Course c) {
        initComponents();
        this.parent = parent;
        this.um = Lab7.userManager;
        this.c = c;
        this.sm =sm;
        this.parent = parent;
        this.cm =cm;
        this.im=im;
        
        loadTable();
        
    }
    

    public void loadTable() {
    DefaultTableModel m = (DefaultTableModel) progressTable.getModel();
    m.setRowCount(0);

    int courseId = c.getCourseId();
    ArrayList<Record> allStudents = sm.read();

    for (Lesson l : c.getLessons()) {
        int lessonId = l.getLessonId();

        double totalScore = 0;
        int totalCompleted = 0;
        int totalEnrolled = 0;

        for (Record r : allStudents) {
            if (!(r instanceof Student)) continue;

            Student stu = (Student) r;

            if (stu.isEnrolled(courseId)) {
                totalEnrolled++;

                if (stu.isLessonCompleted(courseId, lessonId)) {
                    Integer sScore = stu.getQuizScore(courseId, lessonId);
                    if (sScore != null) {
                        totalScore += sScore;
                        totalCompleted++;
                    }
                }
            }
        }

        int totalQuestions = l.getQuiz().getQuestions().size();

        double avgScorePercent = 0;
        if (totalCompleted > 0) {
            avgScorePercent = (totalScore / (totalCompleted * totalQuestions)) * 100;
        }

        double completionPercentage = 0;
        if (totalEnrolled > 0) {
            completionPercentage = (totalCompleted / (double) totalEnrolled) * 100;
        }

  
        l.setQuizAvg(avgScorePercent);
        l.setCompletionPercentage(completionPercentage);

        m.addRow(new Object[]{
            lessonId,
            String.format("%.2f%%", avgScorePercent),
            String.format("%.2f%%", completionPercentage)
        });
    }
}


    public void displayInsights() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (Lesson l : c.getLessons()) {
            double avg = Double.parseDouble(String.valueOf(l.getQuizAvg()));
            dataset.addValue((Number) avg, (Comparable) "Quiz Average", (Comparable) String.valueOf(l.getLessonId()));
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                "Quiz Averages per Lesson",
                "Lesson ID",
                "Average Score",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );

        CategoryPlot plot = (CategoryPlot) barChart.getPlot();
        plot.getRangeAxis().setRange(0, 100);
        plot.setRangeGridlinePaint(java.awt.Color.GRAY);

        JFrame frame = new JFrame("Instructor Dashboard - Quiz Bar Chart");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 500);

        ChartPanel chartPanel = new ChartPanel(barChart);
        frame.add(chartPanel);

        frame.setVisible(true);
        frame.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chartButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        progressTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insights");

        chartButton.setText("Student Performance Chart");
        chartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartButtonActionPerformed(evt);
            }
        });

        progressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "LessonID", "Quiz Average", "Completion Percentage"
            }
        ));
        jScrollPane1.setViewportView(progressTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chartButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(chartButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartButtonActionPerformed
        displayInsights();
    }//GEN-LAST:event_chartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InsightsFrame().setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chartButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable progressTable;
    // End of variables declaration//GEN-END:variables
}
