/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg7;

/**
 *
 * @author Lenovo
 */
public class InstructorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form InstructorManagment
     */
    private Instructor i;
    private InstructorManager im;
    private CourseManager cm;
    private StudentManager sm;
    private UserManager um;

    public InstructorDashboard(UserManager um, CourseManager cm, InstructorManager im, StudentManager sm, Instructor i) {
        initComponents();
        this.i = i;
        this.im = im;
        this.cm = cm;
        this.sm = sm;
        this.um = um;
        userIdTextField.setText("ID:"+String.valueOf(i.getUserId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by he Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mycoursesbutton = new javax.swing.JButton();
        createnewcoursebutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        userIdTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instructor Dashboard");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mycoursesbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mycoursesbutton.setText("My courses");
        mycoursesbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mycoursesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycoursesbuttonActionPerformed(evt);
            }
        });

        createnewcoursebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createnewcoursebutton.setText("Create new course");
        createnewcoursebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createnewcoursebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnewcoursebuttonActionPerformed(evt);
            }
        });

        logoutbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        userIdTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mycoursesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createnewcoursebutton)
                    .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(mycoursesbutton)
                .addGap(33, 33, 33)
                .addComponent(createnewcoursebutton)
                .addGap(35, 35, 35)
                .addComponent(logoutbutton)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mycoursesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycoursesbuttonActionPerformed
        this.dispose();
        new managecourses(this.sm,this.i,this.im, this.cm, this).setVisible(true);
    }//GEN-LAST:event_mycoursesbuttonActionPerformed

    private void createnewcoursebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnewcoursebuttonActionPerformed
        this.dispose();
        new CreateCourse(this.i, this.im, this.cm, this).setVisible(true);
    }//GEN-LAST:event_createnewcoursebuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        this.dispose();
        new LoginFrame(this.um, this.cm, this.im, this.sm).setVisible(true);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
// 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createnewcoursebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton mycoursesbutton;
    private javax.swing.JTextField userIdTextField;
    // End of variables declaration//GEN-END:variables
}
