package lab.pkg7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class managecourses extends javax.swing.JFrame {

    private InstructorManager im;
    private InstructorDashboard parent;
    private CourseManager cm;
    private Instructor ins;
    private StudentManager sm;

    public managecourses(StudentManager sm, Instructor ins, InstructorManager im, CourseManager cm, InstructorDashboard parent) {
        initComponents();
        this.im = im;
        this.parent = parent;
        this.cm = cm;
        this.ins = ins;
        this.sm = sm;

        JsonDatabase.loadCourses(cm);
        JsonDatabase.loadUsers(sm, im);

        SearchTable.setAutoCreateRowSorter(true);
        DefaultTableModel model = (DefaultTableModel) SearchTable.getModel();
        SearchTable.setRowSorter(new TableRowSorter<TableModel>(model));

        loadInstructorCourses();
    }

    private void loadInstructorCourses() {
        DefaultTableModel m = (DefaultTableModel) SearchTable.getModel();
        m.setRowCount(0);

        if (ins == null) {
            return;
        }

        ArrayList<Record> allCourses = cm.read();

        for (Record r : allCourses) {
            if (r instanceof Course) {
                Course c = (Course) r;

                if (c.getInstructorId() == ins.getUserId()) {
                    int lessonCount = (c.getLessons() == null) ? 0 : c.getLessons().size();
                    String studentsStr = buildStudentsString(c);

                    m.addRow(new Object[]{
                        c.getCourseId(),
                        c.getTitle(),
                        c.getDescription(),
                        lessonCount,
                        studentsStr
                    });
                }
            }
        }
    }

    private String buildStudentsString(Course c) {
        ArrayList<Integer> enrolled = c.getEnrolledStudents();
        if (enrolled == null || enrolled.isEmpty()) {
            return "-";
        }

        StringBuilder sb = new StringBuilder();
        boolean first = true;

        for (int sid : enrolled) {
            if (!first) {
                sb.append(", ");
            }
            first = false;

            String name = "Unknown";
            Record r = sm.search(sid);
            if (r instanceof Student) {
                name = ((Student) r).getUsername();
            }

            sb.append(sid).append("-").append(name);
        }
        return sb.toString();
    }

    private void refreshTableWithSingleCourse(Course c) {
        DefaultTableModel m = (DefaultTableModel) SearchTable.getModel();
        m.setRowCount(0);

        int lessonCount = c.getLessons() == null ? 0 : c.getLessons().size();
        String studentsStr = buildStudentsString(c);

        m.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getDescription(),
            lessonCount,
            studentsStr
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        searchByIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchIDtext = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        SearchButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        AgeText = new javax.swing.JScrollPane();
        title = new javax.swing.JTextArea();
        UpdateButton = new javax.swing.JButton();
        Lessons = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        lessonID = new javax.swing.JTextField();
        lessonsTitle = new javax.swing.JTextField();
        lessonsContent = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        ViewenrolledStudents = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        insightsButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchByIDLabel.setText("Search By ID");

        SearchIDtext.setColumns(20);
        SearchIDtext.setRows(5);
        jScrollPane1.setViewportView(SearchIDtext);

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CourseId", "Title", "Description", "Lessons", "Students"
            }
        ));
        jScrollPane4.setViewportView(SearchTable);

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        Title.setText("Title");

        title.setColumns(20);
        title.setRows(5);
        AgeText.setViewportView(title);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        Lessons.setText("Lessons");

        Description.setText("Description");

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });

        lessonID.setText("lesson id");
        lessonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonIDActionPerformed(evt);
            }
        });

        lessonsTitle.setText("title");
        lessonsTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonsTitleActionPerformed(evt);
            }
        });

        lessonsContent.setText("content");
        lessonsContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonsContentActionPerformed(evt);
            }
        });

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        ViewenrolledStudents.setText("View Enrolled Students");
        ViewenrolledStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewenrolledStudentsActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        insightsButton.setText("Insights");
        insightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insightsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchByIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AgeText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(description))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Lessons, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lessonID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lessonsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lessonsContent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(UpdateButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(insightsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deletebutton))
                            .addComponent(ViewenrolledStudents, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchByIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(SearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lessons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lessonsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lessonsContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateButton)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(backButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletebutton)
                            .addComponent(insightsButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewenrolledStudents)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String txt = SearchIDtext.getText().trim();
        if (txt.isEmpty()) {
            return;
        }

        int id;
        try {
            id = Integer.parseInt(txt);
        } catch (Exception e) {
            return;
        }

        Course c = cm.getCourseById(id);
        if (c == null) {
            return;
        }
        if (c.getInstructorId() != ins.getUserId()) {
            return;
        }

        refreshTableWithSingleCourse(c);

    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
    String idText = SearchIDtext.getText().trim();
    if (idText.isEmpty()) return;

    int id = Integer.parseInt(idText);
    Record r = cm.search(id);
    if (!(r instanceof Course)) return;

    Course c = (Course) r;

    if (c.getInstructorId() != ins.getUserId()) return;

    c.setTitle(title.getText().trim());
    c.setDescription(description.getText().trim());

    Lesson newLesson = null;


    if (!lessonID.getText().trim().isEmpty()
            && !lessonsTitle.getText().trim().isEmpty()
            && !lessonsContent.getText().trim().isEmpty()) {

        int lid = Integer.parseInt(lessonID.getText().trim());

        newLesson = new Lesson(
                lid,
                lessonsTitle.getText().trim(),
                lessonsContent.getText().trim(),
                false,0,0
        );

        c.getLessons().add(newLesson);

 
        JsonDatabase.saveCourses(cm);
        JsonDatabase.saveUsers(sm, im);


        AddQuizFrame qf = new AddQuizFrame(
                Lab7.userManager, 
                cm,
                im,
                sm,
                c,
                newLesson,
                this
        );
        qf.setVisible(true);

        JOptionPane.showMessageDialog(this, "Lesson added! Now add quiz.");
        return;
    }


    JsonDatabase.saveCourses(cm);
    JsonDatabase.saveUsers(sm, im);

    JOptionPane.showMessageDialog(this, "Course updated!");
    refreshTableWithSingleCourse(c);
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void lessonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonIDActionPerformed

    private void lessonsTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonsTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonsTitleActionPerformed

    private void lessonsContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonsContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonsContentActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
 int row = SearchTable.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a course first");
        return;
    }

    row = SearchTable.convertRowIndexToModel(row);
    int cId = (int) SearchTable.getModel().getValueAt(row, 0);

    Course c = (Course) cm.search(cId);
    if (c == null) {
        JOptionPane.showMessageDialog(this, "Course not found");
        return;
    }

    if (c.getInstructorId() != ins.getUserId()) {
        JOptionPane.showMessageDialog(this, "You can only delete your courses");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Delete course " + cId + "?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    // Remove from CourseManager
    cm.read().remove(c);

    // Remove from instructor list
    ins.getCreatedCourses().remove(Integer.valueOf(cId));

    // Remove from all students
    for (Record rr : sm.read()) {
        Student st = (Student) rr;
        st.getEnrolledCourses().remove(Integer.valueOf(cId));
    }

    // Save
    JsonDatabase.saveCourses(cm);
    JsonDatabase.saveUsers(sm, im);

    JOptionPane.showMessageDialog(this, "Course deleted successfully");
  

    loadInstructorCourses();    }//GEN-LAST:event_deletebuttonActionPerformed

    private void ViewenrolledStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewenrolledStudentsActionPerformed

        int selected = SearchTable.getSelectedRow();
        if (selected == -1) {
            JOptionPane.showMessageDialog(this, "Select a course first.");
            return;
        }

        selected = SearchTable.convertRowIndexToModel(selected);

        Object val = SearchTable.getModel().getValueAt(selected, 0);
        if (val == null) {
            JOptionPane.showMessageDialog(this, "Invalid course ID.");
            return;
        }

        int courseId;
        try {
            courseId = Integer.parseInt(val.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid course ID format.");
            return;
        }

        Course c = cm.getCourseById(courseId);
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Course not found in course manager.");
            return;
        }

        ArrayList<Integer> enrolled = c.getEnrolledStudents();
        if (enrolled == null || enrolled.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No students enrolled.");
            return;
        }

        StringBuilder sb = new StringBuilder("Enrolled Students:\n\n");
        for (int sid : enrolled) {
            Record sr = sm.search(sid);
            String name = (sr instanceof Student) ? ((Student) sr).getUsername() : "Unknown";
            sb.append(sid).append(" - ").append(name).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString());

    }//GEN-LAST:event_ViewenrolledStudentsActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void insightsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insightsButtonActionPerformed
        int selectedRow = SearchTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course from the table.");
            return;
        }

        int courseId= (int) SearchTable.getValueAt(selectedRow, 0);
        Course selected = (Course) cm.search(courseId);
        
        if(selected == null){
        JOptionPane.showMessageDialog(this, "Course not found.");
        return;
        }
        this.dispose();
        new InsightsFrame(this,this.cm,this.im,this.sm,selected).setVisible(true);

    }//GEN-LAST:event_insightsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    //public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SearchAndUpdate().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AgeText;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Lessons;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextArea SearchIDtext;
    private javax.swing.JTable SearchTable;
    private javax.swing.JLabel Title;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton ViewenrolledStudents;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField description;
    private javax.swing.JButton insightsButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lessonID;
    private javax.swing.JTextField lessonsContent;
    private javax.swing.JTextField lessonsTitle;
    private javax.swing.JLabel searchByIDLabel;
    private javax.swing.JTextArea title;
    // End of variables declaration//GEN-END:variables
}
