/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author youssufathalla
 */
public class StudentCourses extends javax.swing.JFrame {

    /**
     * Creates new form StudentCourses
     */
    private Student s;
    private InstructorManager im;
    private CourseManager cm;
    private StudentManager sm;
    private UserManager um;

    public StudentCourses(UserManager um, CourseManager cm, InstructorManager im, StudentManager sm, Student s) {
        this.s = s;
        this.im = im;
        this.cm = cm;
        this.sm = sm;
        this.um = um;

        JsonDatabase.loadUsers(sm, im);
        JsonDatabase.loadCourses(cm);

        this.s = (Student) sm.search(s.getUserId());

        initComponents();
        loadTable();
    }

    public void loadTable() {
        String prog;
        DefaultTableModel m = (DefaultTableModel) studentCoursesTable.getModel();
        m.setRowCount(0);

        ArrayList<Integer> enrolled = s.getEnrolledCourses();

        for (int courseId : enrolled) {
            Record r = cm.search(courseId);
            if (r == null) {
                continue;
            }

            Course c = (Course) r;
            int x = 0, y = (c.getLessons() == null ? 0 : c.getLessons().size());
            if (c.getLessons() != null) {
                for (Lesson lesson : c.getLessons()) {
                    if (s.isLessonCompleted(c.getCourseId(), lesson.getLessonId())) {
                        x++;
                    }
                }
            }
            s.setProgress((double) (x / y));

            JsonDatabase.saveUsers(sm, im);
            JsonDatabase.loadUsers(sm, im);

            prog = x + "/" + y;

            m.addRow(new Object[]{
                c.getCourseId(),
                c.getTitle(),
                c.getDescription(),
                c.getInstructorId(),
                c.getLessons().size(),
                prog
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        studentCoursesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        opencoursebutton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CourseId", "Title", "Description", "Instructor", "Lessons", "Progress"
            }
        ));
        jScrollPane4.setViewportView(studentCoursesTable);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Courses");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        opencoursebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opencoursebutton.setText("Open course");
        opencoursebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opencoursebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opencoursebuttonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(opencoursebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opencoursebutton)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opencoursebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opencoursebuttonActionPerformed
        int selectedRow = studentCoursesTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course from the table.");
            return;
        }

        int courseId = (int) studentCoursesTable.getValueAt(selectedRow, 0);

        Course selected = (Course) cm.search(courseId);

        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Course not found.");
            return;
        }
        this.dispose();
        new CourseDisplay(this.um, this.cm, this.im, this.sm, this.s, selected).setVisible(true);
    }//GEN-LAST:event_opencoursebuttonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new StudentDashboard(this.um, this.cm, this.im, this.sm, this.s).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton opencoursebutton;
    private javax.swing.JTable studentCoursesTable;
    // End of variables declaration//GEN-END:variables
}
